Add separate download command to download files from ftp

diff --git a/lep b/lep
--- a/lep
+++ b/lep
@@ -36,6 +36,7 @@ lep_usage() {
   printf "%s\n" "Commands:"
   printf "  %s   Initialise episode\n" "init      "
   printf "  %s   Check if ready to start automation\n" "check     "
+  printf "  %s   Download file from ftp server\n" "download  "
   printf "  %s   Generate episode metadata\n" "metadata  "
   printf "  %s   Configure youtube video\n" "youtube   "
   printf "  %s   Upload file to self hosted ftp server\n" "ftp       "
@@ -113,6 +114,41 @@ lep_check_usage() {
     # :flag.usage
     printf "  %s\n" "--skip-youtube"
     printf "    Skip scheduling youtube video\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+lep_download_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "lep download - Download file from ftp server\n"
+    echo
+
+  else
+    printf "lep download - Download file from ftp server\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  lep download [OPTIONS]\n"
+  printf "  lep download --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--file, -f FILE (required)"
+    printf "    File to download\n"
     echo
 
     # :command.usage_fixed_flags
@@ -628,6 +664,15 @@ lep_check_command() {
 }
 
 # :command.function
+lep_download_command() {
+  # src/download_command.sh
+  file=${args[--file]}
+
+  curl https://rssfeed.laufendentdecken-podcast.at/data/$file --output ~/Downloads/$file
+
+}
+
+# :command.function
 lep_metadata_command() {
   # src/metadata_command.sh
   title=${args[--title]}
@@ -1022,7 +1067,8 @@ lep_automation_command() {
   if [[ -z "$skipDownload" ]]; then
       echo
       echo " Download adfree version again to be able to upload it to patroen/steady"
-      curl https://rssfeed.laufendentdecken-podcast.at/data/$slugAdFree.mp3 --output ~/Downloads/$slugAdFree.mp3
+      lep download --file "$slugAdFree.mp3"
+
   fi
 
   if [ $? -ne 0 ]; then
@@ -1282,6 +1328,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    download)
+      action="download"
+      shift
+      lep_download_parse_requirements "$@"
+      shift $#
+      ;;
+
     metadata)
       action="metadata"
       shift
@@ -1452,6 +1505,70 @@ lep_check_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+lep_download_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        lep_download_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="download"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --file | -f)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--file']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--file requires an argument: --file, -f FILE" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--file']+x} ]]; then
+    printf "missing required flag: --file, -f FILE\n" >&2
+    exit 1
+  fi
 
 }
 
@@ -2166,6 +2283,7 @@ run() {
   case "$action" in
     "init") lep_init_command ;;
     "check") lep_check_command ;;
+    "download") lep_download_command ;;
     "metadata") lep_metadata_command ;;
     "youtube") lep_youtube_command ;;
     "ftp") lep_ftp_command ;;
