Upload just a youtube video

diff --git a/lep b/lep
--- a/lep
+++ b/lep
@@ -34,18 +34,19 @@ lep_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Generate bash completions\n" "completions"
-  printf "  %s   Initialize episode\n" "init       "
-  printf "  %s   Edit current episode description\n" "edit       "
-  printf "  %s   Create a new iteration\n" "new        "
-  printf "  %s   Check if ready to start automation\n" "check      "
-  printf "  %s   Download file from ftp server\n" "download   "
-  printf "  %s   Generate episode metadata\n" "metadata   "
-  printf "  %s   Configure youtube video\n" "youtube    "
-  printf "  %s   Upload file to self hosted ftp server\n" "ftp        "
-  printf "  %s   Upload latest episode and start automatic post processing workflow\n" "automation "
-  printf "  %s   Start new auphonic production\n" "auphonic   "
-  printf "  %s   Create wordpress blogpost on http://laufendentdecken-podcast.at\n" "blogpost   "
+  printf "  %s   Generate bash completions\n" "completions   "
+  printf "  %s   Initialize episode\n" "init          "
+  printf "  %s   Edit current episode description\n" "edit          "
+  printf "  %s   Create a new iteration\n" "new           "
+  printf "  %s   Check if ready to start automation\n" "check         "
+  printf "  %s   Download file from ftp server\n" "download      "
+  printf "  %s   Generate episode metadata\n" "metadata      "
+  printf "  %s   Configure youtube video\n" "youtube       "
+  printf "  %s   Upload file to self hosted ftp server\n" "ftp           "
+  printf "  %s   Upload latest episode to youtube and start automatic post processing workflow\n" "upload-youtube"
+  printf "  %s   Upload latest episode and start automatic post processing workflow\n" "automation    "
+  printf "  %s   Start new auphonic production\n" "auphonic      "
+  printf "  %s   Create wordpress blogpost on http://laufendentdecken-podcast.at\n" "blogpost      "
   echo
 
   # :command.long_usage
@@ -373,6 +374,35 @@ lep_ftp_usage() {
     printf "  %s\n" "--name, -n NAME (required)"
     printf "    Name of file on server\n"
     echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+lep_upload_youtube_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "lep upload-youtube - Upload latest episode to youtube and start automatic post processing workflow\n"
+    echo
+
+  else
+    printf "lep upload-youtube - Upload latest episode to youtube and start automatic post processing workflow\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  lep upload-youtube\n"
+  printf "  lep upload-youtube --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -945,7 +975,8 @@ lep_metadata_command() {
   sourceFile="$title.md"
 
   if ! [[ -e $contentFile ]]; then
-      pandoc -s -o $contentFile $sourceFile
+      echo " Generating html content file"
+      pandoc -s -o $contentFile $sourceFile > /dev/null
   fi
 
   if ! [[ -e $dataFile ]]; then
@@ -1003,14 +1034,6 @@ lep_metadata_command() {
   fi
 
   IFS=',' read -r postNumber postTitle postDate <<< "$(head -n 1 "$title"".txt")"
-
-  gum spin \
-      --show-output --spinner minidot --title " Kopiere Titel in Clipboard" \
-      -- echo "LEP#$postNumber - $postTitle" | pbcopy -Prefer r
-
-  gum spin \
-      --show-output --spinner minidot --title " Kopiere Content in Clipboard" \
-      -- pandoc -s -f html -t plain $contentFile | sed -e '1,2d' | tr '\n' ' ' | pbcopy -Prefer r
 
 }
 
@@ -1085,6 +1108,71 @@ lep_ftp_command() {
   server_username=$(op read "op://Podcast/ahvoh5qmumxyrtvih2klge7uqa/username")
 
   curl --user $server_username:$server_pwd --upload-file $file ftp://rssfeed.laufendentdecken-podcast.at/$name
+
+}
+
+# :command.function
+lep_upload_youtube_command() {
+  # src/upload_youtube_command.sh
+  defaultAirTime="09:00:00"
+  episode=$(basename "$(pwd)")
+  episode="$episode.m4a"
+
+  baseUrl="https://rssfeed.laufendentdecken-podcast.at/data/"
+  title=$(echo "$episode" | cut -d'.' -f 1)
+
+  IFS=',' read -r postNumber postTitle postDate <<< "$(head -n 1 "$title"".txt")"
+
+  coverYoutube="$title"_youtube.png
+  coverYoutubeWithPostNumber="$postNumber"_"$coverYoutube"
+  coverUrlYoutube="$baseUrl$coverYoutubeWithPostNumber"
+
+  slug="$postNumber"_"$title"
+  youtubePreset=$(op read "op://Podcast/Auphonic Api/youtubePreset")
+
+  youtubeDescription=$(echo -e "\n\nHört rein auf:\n🔗Https://laufendentdecken.at/$postNumber/\n\nUnd natürlich auf\n🎧Spotify, iTunes, Google Podcast, zencastr und in allen podcatchern über das RSS Feed.\n\n✅ Folge uns auf Instagram @laufendentdeckenpodcast , @floderandere und @redendentdecken\n\nUnd auf Facebook https://www.facebook.com/laufendentdeckenpodcast/\n\nWer uns unterstützen mag: https://www.patreon.com/laufendentdecken\noder Steady: https://steadyhq.com/de/laufendentdecken")
+  episodeWithPostNumber="$postNumber"_"$episode"
+
+  echo "██╗     ███████╗██████╗      ██████╗██╗     ██╗";
+  echo "██║     ██╔════╝██╔══██╗    ██╔════╝██║     ██║";
+  echo "██║     █████╗  ██████╔╝    ██║     ██║     ██║";
+  echo "██║     ██╔══╝  ██╔═══╝     ██║     ██║     ██║";
+  echo "███████╗███████╗██║         ╚██████╗███████╗██║";
+  echo "╚══════╝╚══════╝╚═╝          ╚═════╝╚══════╝╚═╝";
+  echo "                                               ";
+
+  lep check
+
+  if [ $? -ne 0 ]; then
+    exit 1
+  fi
+
+  echo "  Upload youtube cover to FTP Server"
+  lep ftp --file $coverYoutube --name $coverYoutubeWithPostNumber
+
+  if [ $? -ne 0 ]; then
+    exit 1
+  fi
+
+  echo " Automate episode 'LEP#$postNumber - $postTitle' scheduled for $postDate"
+
+  lep auphonic  \
+      --production_name "LEP#$postNumber - $postTitle" \
+      --preset $youtubePreset \
+      --cover_url $coverUrlYoutube \
+      --file $episodeWithPostNumber \
+      --slug $slug \
+      --description "$youtubeDescription"
+
+  if [ $? -ne 0 ]; then
+    exit 1
+  fi
+
+  echo
+  echo " Schedule youtube video"
+  lep youtube \
+      --title "LEP#$postNumber" \
+      --publish_date "$postDate $defaultAirTime"
 
 }
 
@@ -1382,12 +1470,10 @@ lep_auphonic_command() {
 
   action="start"
 
-  # If no start is set, we just want to save the production
   if [[ -n "$noStart" ]]; then
       action="save"
   fi
 
-  echo
   echo
   echo " Create $auphonicTitle Production"
   json=$(curl -s -X POST https://auphonic.com/api/simple/productions.json \
@@ -1402,7 +1488,6 @@ lep_auphonic_command() {
        -F "summary=$description" \
        -F "action=$action")
 
-  # Only query the status if we started the production
   if [[ -z "$noStart" ]]; then
       echo " Production started"
       content=$(echo $json | jq -r ' . | "\(.data.status_string):\(.data.uuid)"')
@@ -1482,9 +1567,10 @@ lep_blogpost_command() {
 
   apiKey=$(op read "op://Podcast/Podlove/credential")
 
-  echo " Initiaing episode"
+  echo " Initiating episode"
 
-  json=$(curl -s -X POST https://laufendentdecken-podcast.at/wp-json/podlove/v2/episodes --header "Authorization: Basic $apiKey")
+  json=$(curl -s -X POST https://laufendentdecken-podcast.at/wp-json/podlove/v2/episodes \
+      --header "Authorization: Basic $apiKey")
 
   episodeId=$(echo $json | jq -r ' . | "\(.id)"')
   response=$(curl -s -X POST https://laufendentdecken-podcast.at/wp-json/podlove/v2/episodes/$episodeId \
@@ -1655,6 +1741,13 @@ parse_requirements() {
       action="ftp"
       shift
       lep_ftp_parse_requirements "$@"
+      shift $#
+      ;;
+
+    upload-youtube)
+      action="upload-youtube"
+      shift
+      lep_upload_youtube_parse_requirements "$@"
       shift $#
       ;;
 
@@ -2261,6 +2354,50 @@ lep_ftp_parse_requirements() {
 }
 
 # :command.parse_requirements
+lep_upload_youtube_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        lep_upload_youtube_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="upload-youtube"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 lep_automation_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -2766,6 +2903,7 @@ run() {
     "metadata") lep_metadata_command ;;
     "youtube") lep_youtube_command ;;
     "ftp") lep_ftp_command ;;
+    "upload-youtube") lep_upload_youtube_command ;;
     "automation") lep_automation_command ;;
     "auphonic") lep_auphonic_command ;;
     "blogpost") lep_blogpost_command ;;
