Add completion to lep command

diff --git a/lep b/lep
--- a/lep
+++ b/lep
@@ -34,15 +34,16 @@ lep_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Initialise episode\n" "init      "
-  printf "  %s   Check if ready to start automation\n" "check     "
-  printf "  %s   Download file from ftp server\n" "download  "
-  printf "  %s   Generate episode metadata\n" "metadata  "
-  printf "  %s   Configure youtube video\n" "youtube   "
-  printf "  %s   Upload file to self hosted ftp server\n" "ftp       "
-  printf "  %s   Upload latest episode and start automatic post processing workflow\n" "automation"
-  printf "  %s   Start new auphonic production\n" "auphonic  "
-  printf "  %s   Create wordpress blogpost on http://laufendentdecken-podcast.at\n" "blogpost  "
+  printf "  %s   Generate bash completions\n" "completions"
+  printf "  %s   Initialise episode\n" "init       "
+  printf "  %s   Check if ready to start automation\n" "check      "
+  printf "  %s   Download file from ftp server\n" "download   "
+  printf "  %s   Generate episode metadata\n" "metadata   "
+  printf "  %s   Configure youtube video\n" "youtube    "
+  printf "  %s   Upload file to self hosted ftp server\n" "ftp        "
+  printf "  %s   Upload latest episode and start automatic post processing workflow\n" "automation "
+  printf "  %s   Start new auphonic production\n" "auphonic   "
+  printf "  %s   Create wordpress blogpost on http://laufendentdecken-podcast.at\n" "blogpost   "
   echo
 
   # :command.long_usage
@@ -55,6 +56,38 @@ lep_usage() {
     echo
     printf "  %s\n" "--version, -v"
     printf "    Show version number\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+lep_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "lep completions\n"
+    echo
+
+    printf "  Generate bash completions\n  Usage: eval \"\$(lep completions)\"\n"
+    echo
+
+  else
+    printf "lep completions - Generate bash completions\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  lep completions\n"
+  printf "  lep completions --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -584,6 +617,97 @@ inspect_args() {
 }
 
 # :command.user_lib
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# lep completion                                           -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_lep_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $'  '
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_lep_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'automation\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--ag1 --debug --force --help --m4a --no-default-releasedate --polestar --skip-auphonic --skip-aws --skip-blogpost --skip-download --skip-ftp --skip-youtube --time -h -m")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'auphonic\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--cover_url --description --file --help --no-start --preset --production_name --slug -c -d -f -h -n -p -s")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'download\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--file --help -f -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'metadata\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--debug --help --no-default-postnumber --no-default-releasedate --title -h -t")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'blogpost\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--ag1 --help --number --polestar --publish_date --slug --title -h -n -p -s -t")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'youtube\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--help --publish_date --title -h -p -t")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'check\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--help --skip-youtube -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'init\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'ftp\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--file --help --name -f -h -n")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'cb\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--ag1 --help --number --polestar --publish_date --slug --title -h -n -p -s -t")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'a\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--cover_url --description --file --help --no-start --preset --production_name --slug -c -d -f -h -n -p -s")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_lep_completions_filter "--help --version -h -v a auphonic automation blogpost cb check completions download ftp init metadata youtube")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'complete -F _lep_completions lep'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 # src/lib/validations/validate_dir_exists.sh
 validate_dir_exists() {
   [[ -d "$1" ]] || echo "must be an existing directory"
@@ -605,6 +729,21 @@ validate_not_empty() {
 }
 
 # :command.command_functions
+# :command.function
+lep_completions_command() {
+  # src/completions_command.sh
+  # Call the `send_completions` function which was added by running:
+  #
+  #   $ bashly add completions
+  #
+  # Users can now enable bash completion for this script by running:
+  #
+  #   $ eval "$(lep completions)"
+  #
+  send_completions
+
+}
+
 # :command.function
 lep_init_command() {
   # src/init_command.sh
@@ -1367,6 +1506,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    completions)
+      action="completions"
+      shift
+      lep_completions_parse_requirements "$@"
+      shift $#
+      ;;
+
     init)
       action="init"
       shift
@@ -1442,6 +1588,50 @@ parse_requirements() {
       ;;
 
   esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+lep_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        lep_completions_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="completions"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2376,6 +2566,7 @@ run() {
   before_hook
 
   case "$action" in
+    "completions") lep_completions_command ;;
     "init") lep_init_command ;;
     "check") lep_check_command ;;
     "download") lep_download_command ;;
