Prefix every episode file with current episode number

diff --git a/lep b/lep
--- a/lep
+++ b/lep
@@ -164,6 +164,11 @@ lep_ftp_usage() {
     printf "    File to upload\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "--name, -n NAME (required)"
+    printf "    Name of file on server\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
@@ -599,11 +604,12 @@ lep_youtube_command() {
 lep_ftp_command() {
   # src/ftp_command.sh
   file=${args[--file]}
+  name=${args[--name]}
 
   server_pwd=$(op item get "LEP_FTP" --format json | jq -r '. | .fields | .[] | select(.label=="password") | .value')
   server_username=$(op item get "LEP_FTP" --format json | jq -r '. | .fields | .[] | select(.label=="username") | .value')
 
-  curl --user $server_username:$server_pwd --upload-file $file ftp://rssfeed.laufendentdecken-podcast.at
+  curl --user $server_username:$server_pwd --upload-file $file ftp://rssfeed.laufendentdecken-podcast.at/$name
 
 }
 
@@ -683,23 +689,31 @@ lep_automation_command() {
   coverYoutube="$title"_youtube.png
   baseUrl="https://rssfeed.laufendentdecken-podcast.at/data/"
 
-  coverUrl="$baseUrl$cover"
-  coverUrlYoutube="$baseUrl$coverYoutube"
+  coverWithPostNumber="$postNumber"_"$cover"
+  coverYoutubeWithPostNumber="$postNumber"_"$coverYoutube"
+
+  coverUrl="$baseUrl$coverWithPostNumber"
+  coverUrlYoutube="$baseUrl$coverYoutubeWithPostNumber"
+
+  episodeWithPostNumber="$postNumber"_"$episode"
+  episodeAdFreeWithPostNumber="$postNumber"_"$episodeAdFree"
+  slug="$postNumber"_"$title"
+  slugAdFree="$postNumber"_"$titleAdFree"
 
   if [[ -z "$skipFtp" ]]; then
       echo
       echo "Upload episode to FTP Server"
-      lep ftp --file $episode
+      lep ftp --file $episode --name $episodeWithPostNumber
 
       if [[ "$add" = "true" ]]; then
           echo "Upload addfree episode to FTP Server"
-          lep ftp --file $episodeAdFree
+          lep ftp --file $episodeAdFree --name $episodeAdFreeWithPostNumber
       fi
 
       echo "Upload cover to FTP Server"
-      lep ftp --file $cover
+      lep ftp --file $cover --name $coverWithPostNumber
       echo "Upload youtube cover to FTP Server"
-      lep ftp --file $coverYoutube
+      lep ftp --file $coverYoutube --name $coverYoutubeWithPostNumber
 
   fi
 
@@ -711,12 +725,12 @@ lep_automation_command() {
       echo
       echo "Backup to S3"
 
-      aws s3 cp $episode s3://laufendentdecken-podcast/
-      aws s3 cp s3://laufendentdecken-podcast/$episode s3://laufendentdecken-podcast-backup/
+      aws s3 cp $episode s3://laufendentdecken-podcast/$episodeWithPostNumber
+      aws s3 cp s3://laufendentdecken-podcast/$episodeWithPostNumber s3://laufendentdecken-podcast-backup/
 
       if [[ "$add" = "true" ]]; then
-          aws s3 cp $episodeAdFree s3://laufendentdecken-podcast/
-          aws s3 cp s3://laufendentdecken-podcast/$episodeAdFree s3://laufendentdecken-podcast-backup/
+          aws s3 cp $episodeAdFree s3://laufendentdecken-podcast/$episodeAdFreeWithPostNumber
+          aws s3 cp s3://laufendentdecken-podcast/$episodeAdFreeWithPostNumber s3://laufendentdecken-podcast-backup/
       fi
   fi
 
@@ -734,15 +748,15 @@ lep_automation_command() {
           --production_name $title \
           --preset $episodePreset\
           --cover_url $coverUrl \
-          --file $episode \
-          --slug $title
+          --file $episodeWithPostNumber \
+          --slug $slug
 
       lep auphonic  \
           --production_name "LEP#$postNumber - $postTitle" \
           --preset $youtubePreset \
           --cover_url $coverUrlYoutube \
-          --file $episode \
-          --slug $title \
+          --file $episodeWithPostNumber \
+          --slug $slug \
           --description "$youtubeDescription"
 
       if [[ "$add" = "true" ]]; then
@@ -750,8 +764,8 @@ lep_automation_command() {
               --production_name "$title (addfree)" \
               --preset $episodePreset \
               --cover_url $coverUrl \
-              --file $episodeAdFree \
-              --slug $title
+              --file $episodeAdFreeWithPostNumber \
+              --slug $slugAdFree
       fi
 
       echo "Podcast successfully uploaded"
@@ -764,7 +778,7 @@ lep_automation_command() {
   if [[ -z "$skipDownload" ]]; then
       echo
       echo "Download adfree version again to be able to upload it to patroen/steady"
-      curl https://rssfeed.laufendentdecken-podcast.at/data/$titleAdFree.mp3 --output ~/Downloads/$titleAdFree.mp3
+      curl https://rssfeed.laufendentdecken-podcast.at/data/$slugAdFree.mp3 --output ~/Downloads/$slugAdFree.mp3
   fi
 
   if [ $? -ne 0 ]; then
@@ -780,7 +794,7 @@ lep_automation_command() {
               --number $postNumber \
               --title "$postTitle" \
               --publish_date $postDate \
-              --slug $title
+              --slug $slug
       fi
 
       if [[ -n "$ag1" ]]; then
@@ -788,7 +802,7 @@ lep_automation_command() {
               --number $postNumber \
               --title "$postTitle" \
               --publish_date $postDate \
-              --slug $title \
+              --slug $slug \
               --ag1
       fi
 
@@ -1249,6 +1263,21 @@ lep_ftp_parse_requirements() {
         fi
         ;;
 
+      # :flag.case
+      --name | -n)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--name']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--name requires an argument: --name, -n NAME" >&2
+          exit 1
+        fi
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -1268,6 +1297,10 @@ lep_ftp_parse_requirements() {
   # :command.required_flags_filter
   if [[ -z ${args['--file']+x} ]]; then
     printf "missing required flag: --file, -f FILE\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['--name']+x} ]]; then
+    printf "missing required flag: --name, -n NAME\n" >&2
     exit 1
   fi
 
