Define pandoc as a dependency

diff --git a/lep b/lep
--- a/lep
+++ b/lep
@@ -1347,6 +1347,14 @@ parse_requirements() {
     exit 1
   fi
 
+  if command -v pandoc >/dev/null 2>&1; then
+    deps['pandoc']="$(command -v pandoc | head -n1)"
+  else
+    printf "missing dependency: pandoc\n" >&2
+    printf "%s\n" "install by running: 'brew install pandoc'" >&2
+    exit 1
+  fi
+
   # :command.command_filter
   action=${1:-}
 
