Create and properly detect multiple versions of podcast episode

diff --git a/lep b/lep
--- a/lep
+++ b/lep
@@ -37,6 +37,7 @@ lep_usage() {
   printf "  %s   Generate bash completions\n" "completions"
   printf "  %s   Initialize episode\n" "init       "
   printf "  %s   Edit current episode description\n" "edit       "
+  printf "  %s   Create a new iteration\n" "new        "
   printf "  %s   Check if ready to start automation\n" "check      "
   printf "  %s   Download file from ftp server\n" "download   "
   printf "  %s   Generate episode metadata\n" "metadata   "
@@ -138,6 +139,35 @@ lep_edit_usage() {
   printf "%s\n" "Usage:"
   printf "  lep edit\n"
   printf "  lep edit --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+lep_new_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "lep new - Create a new iteration\n"
+    echo
+
+  else
+    printf "lep new - Create a new iteration\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  lep new\n"
+  printf "  lep new --help | -h\n"
   echo
 
   # :command.long_usage
@@ -794,14 +824,46 @@ lep_edit_command() {
 }
 
 # :command.function
+lep_new_command() {
+  # src/new_command.sh
+  #!/bin/bash
+
+  baseName=$(basename "$(pwd)")
+  newBaseName=$(basename "$(pwd)")
+  episode="$baseName.m4a"
+  counter=1
+  latestCounter=1
+
+  while [ -e "$episode" ]; do
+      episode="$baseName-$counter.m4a"
+      latestCounter=$counter
+      ((counter++))
+  done
+
+  cp "$baseName.md" "$baseName-$latestCounter.md"
+  cp "$baseName.txt" "$latestCounter.txt"
+  cp "$baseName.png" "$latestCounter.png"
+
+}
+
+# :command.function
 lep_check_command() {
   # src/check_command.sh
   skipYoutube=${args[--skip-youtube]}
 
   folder=$(basename "$(pwd)")
+  episode=$folder
   error=0
+  counter=1
 
-  if [[ -e "$folder.m4a" ]]; then
+  while [ -e "$folder-$counter.m4a" ]; do
+      episode="$folder-$counter"
+      ((counter++))
+  done
+
+  echo "Checking for $episode.m4a"
+
+  if [[ -e "$episode.m4a" ]]; then
       echo -e "\e[32m Episode is already exported\e[0m"
   else
 
@@ -809,13 +871,13 @@ lep_check_command() {
       error=1
   fi
 
-  if [[ -e "${folder}_adfree.m4a" ]]; then
+  if [[ -e "${episode}_adfree.m4a" ]]; then
       echo -e "\e[32m Adfree Episode is already exported\e[0m"
   else
       echo -e "\e[33m No Adfree Episode \e[0m"
   fi
 
-  if [[ -e "$folder.md" ]]; then
+  if [[ -e "$episode.md" ]]; then
       echo -e "\e[32m Episode description exists\e[0m"
   else
 
@@ -823,7 +885,7 @@ lep_check_command() {
       error=1
   fi
 
-  if [[ -s "$folder.md" ]]; then
+  if [[ -s "$episode.md" ]]; then
       echo -e "\e[32m Episode description is not empty\e[0m"
   else
 
@@ -831,7 +893,7 @@ lep_check_command() {
       error=1
   fi
 
-  if [[ -e "$folder.png" ]]; then
+  if [[ -e "$episode.png" ]]; then
       echo -e "\e[32m Episode thumbnail exists\e[0m"
   else
 
@@ -840,7 +902,7 @@ lep_check_command() {
   fi
 
   if [[ -z "$skipYoutube" ]]; then
-      if [[ -e "${folder}_youtube.png" ]]; then
+      if [[ -e "${episode}_youtube.png" ]]; then
           echo -e "\e[32m Episode youtube thumbnail exists\e[0m"
       else
 
@@ -849,7 +911,7 @@ lep_check_command() {
       fi
   fi
 
-  if [[ -e "$folder.chapters.txt" ]]; then
+  if [[ -e "$episode.chapters.txt" ]]; then
       echo -e "\e[32m Episode chapters exists\e[0m"
   else
 
@@ -1554,6 +1616,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    new)
+      action="new"
+      shift
+      lep_new_parse_requirements "$@"
+      shift $#
+      ;;
+
     check)
       action="check"
       shift
@@ -1754,6 +1823,50 @@ lep_edit_parse_requirements() {
 
   # :command.command_filter
   action="edit"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+lep_new_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        lep_new_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="new"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -2647,6 +2760,7 @@ run() {
     "completions") lep_completions_command ;;
     "init") lep_init_command ;;
     "edit") lep_edit_command ;;
+    "new") lep_new_command ;;
     "check") lep_check_command ;;
     "download") lep_download_command ;;
     "metadata") lep_metadata_command ;;
