Let ollama generate seo meta description

diff --git a/lep b/lep
--- a/lep
+++ b/lep
@@ -1547,6 +1547,8 @@ lep_blogpost_command() {
       description=""
   fi
 
+  seoMetaDescription=$(ollama run mistral "Act as an seo expert and assist me in writing an SEO metadescription. Please provide your answer in german, not english. What I need from you is exactly one sentence (not longer) that summarizes the input: $(cat $title.md). Please don't use more then 50 words'")
+
   case $postTitle in
       "Ein Gespräch mit "*)
           guest=${postTitle#"Ein Gespräch mit "}
@@ -1599,7 +1601,7 @@ lep_blogpost_command() {
       --form "title=$name" \
       | jq -r '.id')
 
-  postData="{ \"featured_media\": $featureMedia, \"title\":\"$fullPostTitle\", \"status\": \"future\", \"date\": \"$postDate\", \"slug\": \"$postNumber\", \"content\": \"<!-- wp:paragraph -->$description<!-- /wp:paragraph --> <!-- wp:paragraph -->$content<!-- /wp:paragraph -->\" }"
+  postData="{ \"yoast_wpseo_metadesc\": $seoMetaDescription, \"featured_media\": $featureMedia, \"title\":\"$fullPostTitle\", \"status\": \"future\", \"date\": \"$postDate\", \"slug\": \"$postNumber\", \"content\": \"<!-- wp:paragraph -->$description<!-- /wp:paragraph --> <!-- wp:paragraph -->$content<!-- /wp:paragraph -->\" }"
 
   echo " Updating information"
 
@@ -1690,6 +1692,14 @@ parse_requirements() {
   else
     printf "missing dependency: gum\n" >&2
     printf "%s\n" "install by running: 'brew install gum'" >&2
+    exit 1
+  fi
+
+  if command -v ollama >/dev/null 2>&1; then
+    deps['ollama']="$(command -v ollama | head -n1)"
+  else
+    printf "missing dependency: ollama\n" >&2
+    printf "%s\n" "install by running: 'brew install ollama'" >&2
     exit 1
   fi
 
